//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalFrontier_net.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/LunchService", ConfigurationName="ServiceReference1.LunchService")]
    public interface LunchService {
        
        // CODEGEN: Parameter 'restaurant' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FinalFrontier_net.ServiceReference1.addOrderResponse addOrder(FinalFrontier_net.ServiceReference1.addOrder request);
        
        // CODEGEN: Parameter 'RestaurantList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RestaurantList")]
        FinalFrontier_net.ServiceReference1.getRestaurantsResponse getRestaurants(FinalFrontier_net.ServiceReference1.getRestaurants request);
        
        // CODEGEN: Parameter 'MenuList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="MenuList")]
        FinalFrontier_net.ServiceReference1.getMenuResponse getMenu(FinalFrontier_net.ServiceReference1.getMenu request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/LunchService")]
    public partial class restaurant : object, System.ComponentModel.INotifyPropertyChanged {
        
        private menuItem[] menuField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("menuItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public menuItem[] menu {
            get {
                return this.menuField;
            }
            set {
                this.menuField = value;
                this.RaisePropertyChanged("menu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/LunchService")]
    public partial class menuItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string menuStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string menuString {
            get {
                return this.menuStringField;
            }
            set {
                this.menuStringField = value;
                this.RaisePropertyChanged("menuString");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addOrder", WrapperNamespace="http://localhost/LunchService", IsWrapped=true)]
    public partial class addOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/LunchService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FinalFrontier_net.ServiceReference1.restaurant restaurant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/LunchService", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("menuItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FinalFrontier_net.ServiceReference1.menuItem[] menuItems;
        
        public addOrder() {
        }
        
        public addOrder(FinalFrontier_net.ServiceReference1.restaurant restaurant, FinalFrontier_net.ServiceReference1.menuItem[] menuItems) {
            this.restaurant = restaurant;
            this.menuItems = menuItems;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addOrderResponse", WrapperNamespace="http://localhost/LunchService", IsWrapped=true)]
    public partial class addOrderResponse {
        
        public addOrderResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRestaurants", WrapperNamespace="http://localhost/LunchService", IsWrapped=true)]
    public partial class getRestaurants {
        
        public getRestaurants() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRestaurantsResponse", WrapperNamespace="http://localhost/LunchService", IsWrapped=true)]
    public partial class getRestaurantsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/LunchService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RestaurantList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FinalFrontier_net.ServiceReference1.restaurant[] RestaurantList;
        
        public getRestaurantsResponse() {
        }
        
        public getRestaurantsResponse(FinalFrontier_net.ServiceReference1.restaurant[] RestaurantList) {
            this.RestaurantList = RestaurantList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMenu", WrapperNamespace="http://localhost/LunchService", IsWrapped=true)]
    public partial class getMenu {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/LunchService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FinalFrontier_net.ServiceReference1.restaurant restaurant;
        
        public getMenu() {
        }
        
        public getMenu(FinalFrontier_net.ServiceReference1.restaurant restaurant) {
            this.restaurant = restaurant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMenuResponse", WrapperNamespace="http://localhost/LunchService", IsWrapped=true)]
    public partial class getMenuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/LunchService", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("menuItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FinalFrontier_net.ServiceReference1.menuItem[] MenuList;
        
        public getMenuResponse() {
        }
        
        public getMenuResponse(FinalFrontier_net.ServiceReference1.menuItem[] MenuList) {
            this.MenuList = MenuList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LunchServiceChannel : FinalFrontier_net.ServiceReference1.LunchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LunchServiceClient : System.ServiceModel.ClientBase<FinalFrontier_net.ServiceReference1.LunchService>, FinalFrontier_net.ServiceReference1.LunchService {
        
        public LunchServiceClient() {
        }
        
        public LunchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LunchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LunchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LunchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinalFrontier_net.ServiceReference1.addOrderResponse FinalFrontier_net.ServiceReference1.LunchService.addOrder(FinalFrontier_net.ServiceReference1.addOrder request) {
            return base.Channel.addOrder(request);
        }
        
        public void addOrder(FinalFrontier_net.ServiceReference1.restaurant restaurant, FinalFrontier_net.ServiceReference1.menuItem[] menuItems) {
            FinalFrontier_net.ServiceReference1.addOrder inValue = new FinalFrontier_net.ServiceReference1.addOrder();
            inValue.restaurant = restaurant;
            inValue.menuItems = menuItems;
            FinalFrontier_net.ServiceReference1.addOrderResponse retVal = ((FinalFrontier_net.ServiceReference1.LunchService)(this)).addOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinalFrontier_net.ServiceReference1.getRestaurantsResponse FinalFrontier_net.ServiceReference1.LunchService.getRestaurants(FinalFrontier_net.ServiceReference1.getRestaurants request) {
            return base.Channel.getRestaurants(request);
        }
        
        public FinalFrontier_net.ServiceReference1.restaurant[] getRestaurants() {
            FinalFrontier_net.ServiceReference1.getRestaurants inValue = new FinalFrontier_net.ServiceReference1.getRestaurants();
            FinalFrontier_net.ServiceReference1.getRestaurantsResponse retVal = ((FinalFrontier_net.ServiceReference1.LunchService)(this)).getRestaurants(inValue);
            return retVal.RestaurantList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinalFrontier_net.ServiceReference1.getMenuResponse FinalFrontier_net.ServiceReference1.LunchService.getMenu(FinalFrontier_net.ServiceReference1.getMenu request) {
            return base.Channel.getMenu(request);
        }
        
        public FinalFrontier_net.ServiceReference1.menuItem[] getMenu(FinalFrontier_net.ServiceReference1.restaurant restaurant) {
            FinalFrontier_net.ServiceReference1.getMenu inValue = new FinalFrontier_net.ServiceReference1.getMenu();
            inValue.restaurant = restaurant;
            FinalFrontier_net.ServiceReference1.getMenuResponse retVal = ((FinalFrontier_net.ServiceReference1.LunchService)(this)).getMenu(inValue);
            return retVal.MenuList;
        }
    }
}
